### PR TITLE
Partially Implement Course Filter Button Backend

### LINKED ISSUE #11: Add Real Functionality of the Filter button
Estimated Effort: 8 hours
Dependencies: Issue https://github.com/CMU-313/spring24-nodebb-caffiends/issues/10
Acceptance Criteria:
-Users can be able to filter the posts by course, author, categories or none when chosen the respective options

### PR DESCRIPTION
**Pull request by STWMichael**
Partially resolves #11
- Added Unit Test in test/filterCourseTest.js
- Created handleFilter.ts 
- Linked the handleFilter.ts File with category.js 
- Created UserGuide.md
Ideal Implementation should: 
- Allow user to filter all of the topics in every category by Course name
- Allow user to filter all of the topics in every category by Author name

### CODE REVIEW

**Comment by gercokim** [comment]
Code and tests look good to go. Liked the comments you added

**Comment by kateyslee** [comment]
Code looks like a good attempt. Could you explain more in your description what works and what doesn't?

**Review by kateyslee — APPROVED** [review]

**Review by gercokim — COMMENTED** [review]
Bumping what Kate said: Add a description about tests in UserGuide.md

**Review by gercokim — APPROVED** [review]

**Review by FloodedBee — COMMENTED** [review]
The code looks good to go. Merge approved

**Comment by kateyslee** [comment]
Looks great. You can resolve your merge conflicts and push!

**Pull request merged**
