### PR TITLE
Implemented functionality of classLabels and documentation

### PR DESCRIPTION
**Pull request by gercokim**
- implemented the backend so that post data contains the classLabel that was selected in the composer UI, related to issue #5 
- implemented user interaction with classLabels so that users can only view and select classLabels of groups that they are a member of in the composer UI, addressing issue #4 
- implemented the functionality of classLabels, i.e. users can only view the posts tagged with the classLabel of a group in that group's page, addressing issue #5 
- Added a visual indicator for posts that have a classLabel, so that users can view which group the post is relevant to, and clicking on the visual redirects to the group page #6 
- Wrote documentation on my implemented features, as well as tests - read UserGuide.md for a detailed description of all my changes
- Screenshots for my features are available in the UserGuide.md, as well as the images/ directory
- The features were tested by writing unit tests that ensure the backend is correct and that the classLabel functionality works as intended - more details can be found in UserGuide.md

### CODE REVIEW

**Comment by kateyslee** [comment]
Code and documentation looks good to me, I don't think the tests should be failing so update me

**Comment by STWMichael** [comment]
I think the code looks good to me, tests are passing

**Review by STWMichael — APPROVED** [review]
Code looks good, approving merge request

**Comment by FloodedBee** [comment]
The code seems fine to me. The majority of tests are passing, which indicates functioning code. The merge request is approved.

**Pull request merged**
